/*
 * Decompiled with CFR 0.152.
 */
package Client;

import Server.Buffstat;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import tools.Pair;

public enum SecondaryStat implements Buffstat
{
    IndiePAD(0, true),
    IndieMAD(1, true),
    IndiePDD(2, true),
    IndieMHP(3, true),
    IndieMHPR(4, true),
    IndieMMP(5, true),
    IndieMMPR(6, true),
    IndieACC(7, true),
    IndieEVA(8, true),
    IndieJump(9, true),
    IndieSpeed(10, true),
    IndieAllStat(11, true),
    IndieStatRBasic(12, true),
    IndieDodgeCriticalTime(13, true),
    IndieEXP(14, true),
    IndieBooster(15, true),
    IndieFixedDamageR(16, true),
    PyramidStunBuff(17, true),
    PyramidFrozenBuff(18, true),
    PyramidFireBuff(19, true),
    PyramidBonusDamageBuff(20, true),
    IndieRelaxEXP(21, true),
    IndieSTR(22, true),
    IndieDEX(23, true),
    IndieINT(24, true),
    IndieLUK(25, true),
    IndieDamR(26, true),
    IndieScriptBuff(27, true),
    IndieMDF(28, true),
    IndieAsrR(29, true),
    IndieTerR(30, true),
    IndieCr(31, true),
    IndiePDDR(32, true),
    IndieCD(33, true),
    IndieBDR(34, true),
    IndieStatR(35, true),
    IndieStance(36, true),
    IndieIgnoreMobpdpR(37, true),
    IndieEmpty(38, true),
    IndiePADR(39, true),
    IndieMADR(40, true),
    IndieEVAR(41, true),
    IndieDrainHP(42, true),
    IndiePMdR(43, true),
    IndieForceJump(44, true),
    IndieForceSpeed(45, true),
    IndieQrPointTerm(46, true),
    IndieLoopEffect(47, true),
    IndiePeriodicalSkillActivation(48, true),
    IndieEventForSkill(49, true),
    IndieItemDropRate(50, true),
    IndieBuffIcon(51, true),
    IndieCooltimeReduce(52, true),
    IndieNotDamaged(53, true),
    IndieKeydown(54, true),
    IndieDamReduceR(55, true),
    IndieSpecificSkill(56, true),
    IndieEVARReduceR(57, true),
    IndieHitDamR(58, true),
    IndieApplySuperStance(59, true),
    IndieFlyAcc(60, true),
    IndieAllHitDamR(61, true),
    IndieArc(62, true),
    IndieAut(63, true),
    IndiePowerGuard(64, true),
    IndieDropPer(65, true),
    IndieMesoAmountRate(66, true),
    IndieCheckTimeByClient(67, true),
    IndieDotHealHP(68, true),
    IndieDotHealMP(69, true),
    IndieNormalDamReduceR(70, true),
    IndieIgnorePCounter(71, true),
    IndieBarrier(72, true),
    IndieStarForce(73, true),
    IndieNBDR(74, true),
    IndieMonsterCollectionR(75, true),
    IndieMPConReduceR(76, true),
    IndieAntiMagicShell(77, true),
    IndieDecDamTargetMob(78, true),
    IndieStatCount(79, true),
    PAD(80),
    PDD(81),
    MAD(82),
    ACC(83),
    EVA(84),
    Craft(85),
    Speed(86),
    Jump(87),
    MagicGuard(88),
    DarkSight(89),
    Booster(90),
    PowerGuard(91),
    MaxHP(92),
    MaxMP(93),
    Invincible(94),
    SoulArrow(95),
    Stun(96),
    Poison(97),
    Seal(98),
    Darkness(99),
    ComboCounter(100),
    BlessedHammer(101),
    BlessedHammerActive(102),
    WeaponCharge(103),
    HolySymbol(104),
    MesoUp(105),
    ShadowPartner(106),
    ThiefSteal(107),
    PickPocket(108),
    BloodyExplosion(109),
    Thaw(110),
    Weakness(111),
    Curse(112),
    Slow(113),
    Morph(114),
    Regen(115),
    UNK_116(116),
    Stance(117),
    SharpEyes(118),
    ManaReflection(119),
    Attract(120),
    NoBulletConsume(121),
    Infinity(122),
    AdvancedBless(123),
    IllusionStep(124),
    Blind(125),
    Concentration(126),
    BanMap(127),
    MaxLevelBuff(128),
    MesoUpByItem(129),
    MesoAmountRate(130),
    MesoAmountRateRune(131),
    Ghost(132),
    Barrier(133),
    ReverseInput(134),
    ItemUpByItem(135),
    RespectPImmune(136),
    RespectMImmune(137),
    DefenseAtt(138),
    DefenseState(139),
    DojangBerserk(140),
    DojangInvincible(141),
    DojangShield(142),
    SoulMasterFinal(143),
    WindBreakerFinal(144),
    KarmaBlade(145),
    ElementalReset(167),
    HideAttack(147),
    EventRate(148),
    ComboAbilityBuff(149),
    ComboDrain(150),
    RepeatEffect(151),
    ExpBuffRate(152),
    StopPortion(153),
    StopMotion(154),
    Fear(155),
    HiddenPieceOn(156),
    MagicShield(157),
    MagicResistance(158),
    SoulStone(159),
    Flying(160),
    Frozen(161),
    AssistCharge(162),
    Enrage(163),
    DrawBack(164),
    NotDamaged(165),
    FinalCut(166),
    HowlingAttackDamage(167),
    BeastForm(168),
    Dance(169),
    EMHP(170),
    EMMP(171),
    EPAD(172),
    EMAD(173),
    EPDD(174),
    Guard(175),
    Cyclone(176),
    MorphAvatar(177),
    RidingExpireInfoSave(178),
    NextSpecificSkillDamageUp(179),
    PinkbeanMinibeenMove(180),
    GravityConstraint(181),
    Sneak(182),
    Mechanic(183),
    BeastFormMaxHP(184),
    Dice(185),
    BlessingArmor(186),
    DamR(187),
    TeleportMasteryOn(188),
    CombatOrders(189),
    Beholder(190),
    DispelItemOption(191),
    Inflation(192),
    OnixDivineProtection(193),
    Web(194),
    Bless(195),
    TimeBomb(196),
    DisOrder(197),
    Thread(198),
    Team(199),
    Explosion(200),
    BuffLimit(201),
    STR(202),
    INT(203),
    DEX(204),
    LUK(205),
    DispelItemOptionByField(206),
    DarkTornado(207),
    PVPDamage(208),
    PvPScoreBonus(209),
    PvPInvincible(210),
    PvPRaceEffect(211),
    WeaknessMdamage(212),
    Frozen2(213),
    PVPDamageSkill(214),
    AmplifyDamage(215),
    Shock(216),
    InfinityForce(217),
    IncMaxHP(218),
    IncMaxMP(219),
    HolyMagicShell(220),
    KeyDownTimeIgnore(221),
    ArcaneAim(222),
    MasterMagicOn(223),
    AsrR(224),
    TerR(225),
    DamAbsorbShield(226),
    DevilishPower(227),
    Roulette(228),
    RouletteStack(229),
    SpiritLink(230),
    AsrRByItem(231),
    Event(232),
    CriticalBuff(233),
    DropRate(234),
    PlusExpRate(235),
    ItemInvincible(236),
    Awake(237),
    ItemCritical(238),
    ItemEvade(239),
    Event2(240),
    VampiricTouch(241),
    DDR(242),
    IncTerR(243),
    IncAsrR(244),
    DeathMark(245),
    UsefulAdvancedBless(246),
    Lapidification(247),
    VenomSnake(248),
    CarnivalAttack(249),
    CarnivalDefence(250),
    CarnivalExp(251),
    SlowAttack(252),
    PyramidEffect(253),
    HollowPointBullet(254),
    KeyDownMoving(255),
    IgnoreTargetDEF(256),
    StrikerElectricUsed(257),
    ReviveOnce(258),
    Invisible(259),
    EnrageCr(260),
    EnrageCrDamMin(261),
    Judgement(262),
    DojangLuckyBonus(263),
    PainMark(264),
    Magnet(265),
    MagnetArea(266),
    GuidedArrow(267),
    StraightForceAtomTargets(268),
    LefBuffMastery(269),
    TempSecondaryStat(270),
    CoalitionSupportSoldierStorm(271),
    LefMageLinkSkill(272),
    SixthJavelinStack(273),
    SixthGloryWingJavelinStack(274),
    SixthCrystalStack(275),
    ShadowMomentum(276),
    GrandCross(277),
    YetiCook(278),
    PinkbeanCheer(279),
    DropPer(280),
    VampDeath(281),
    BlessingArmorIncPAD(282),
    KeyDownAreaMoving(283),
    Larkness(284),
    StackBuff(285),
    AntiMagicShell(286),
    LifeTidal(287),
    HitCriDamR(288),
    SmashStack(289),
    PartyBarrier(290),
    ReshuffleSwitch(291),
    SpecialAction(292),
    VampDeathSummon(293),
    StopForceAtomInfo(294),
    SoulGazeCriDamR(295),
    SoulRageCount(296),
    PowerTransferGauge(297),
    AffinitySlug(298),
    Trinity(299),
    IncMaxDamage(300),
    BossShield(301),
    MobZoneState(302),
    GiveMeHeal(303),
    TouchMe(304),
    Contagion(305),
    SoulExalt(306),
    IgnoreAllCounter(307),
    IgnorePImmune(308),
    IgnoreAllImmune(309),
    IgnoreAllAbout(310),
    FinalJudgement(311),
    FireAura(312),
    VengeanceOfAngel(313),
    HeavensDoor(314),
    Preparation(315),
    BullsEye(316),
    IncEffectHPPotion(317),
    IncEffectMPPotion(318),
    BleedingToxin(319),
    IgnoreMobDamR(320),
    Asura(321),
    MegaSmasher(322),
    FlipTheCoin(323),
    UnityOfPower(324),
    Stimulate(325),
    ReturnTeleport(326),
    DropRIncrease(327),
    IgnoreMobpdpR(328),
    BdR(329),
    CapDebuff(330),
    Exceed(331),
    DiabolikRecovery(332),
    SurpassLimit(333),
    FinalAttackProp(334),
    ExceedOverload(335),
    OverloadCount(336),
    BuckShot(337),
    FireBomb(338),
    HalfstatByDebuff(339),
    SurplusSupply(340),
    SetBaseDamage(341),
    EVAR(342),
    NewFlying(343),
    AmaranthGenerator(344),
    CygnusElementSkill(345),
    StrikerHyperElectric(346),
    EventPointAbsorb(347),
    EventAssemble(348),
    StormBringer(349),
    ACCR(350),
    DEXR(351),
    Translucence(352),
    PoseType(353),
    CosmicForge(354),
    ElementSoul(355),
    CosmicOrb(356),
    GlimmeringTime(357),
    TrueSight(358),
    SoulExplosion(359),
    SoulMP(360),
    FullSoulMP(361),
    SoulSkillDamageUp(362),
    ElementalCharge(363),
    Restoration(364),
    CrossOverChain(365),
    Reincarnation(366),
    ReincarnationMission(367),
    ReincarnationOnOff(368),
    ChillingStep(369),
    DotBasedBuff(370),
    SixthDotBasedBuff(371),
    BlessEnsenble(372),
    ComboCostInc(373),
    NaviFlying(374),
    Holding(375),
    QuiverCatridge(376),
    UserControlMob(377),
    ImmuneBarrier(378),
    CriticalGrowing(379),
    LastUseSkillAttr(380),
    QuickDraw(381),
    BowMasterConcentration(382),
    TimeFastABuff(383),
    TimeFastBBuff(384),
    GatherDropR(385),
    AimBox2D(386),
    CursorSniping(387),
    DebuffTolerance(388),
    TearsOfFairy(389),
    DotHealHPPerSecond(390),
    DotHealMPPerSecond(391),
    SpiritGuard(392),
    EunwolUnleashFoxOrb(393),
    PreReviveOnce(394),
    SetBaseDamageByBuff(395),
    LimitMP(396),
    ReflectDamR(397),
    ComboTempest(398),
    MHPCutR(399),
    MMPCutR(400),
    SelfWeakness(401),
    ElementDarkness(402),
    FlareTrick(403),
    FlameDischarge(404),
    Dominion(405),
    SiphonVitality(406),
    DarknessAscension(407),
    BossWaitingLinesBuff(408),
    DamageReduce(409),
    ShadowServant(410),
    ShadowIllusion(411),
    KnockBack(412),
    AddAttackCount(413),
    ComplusionSlant(414),
    JaguarSummoned(415),
    JaguarCount(416),
    SSFShootingAttack(417),
    DevilCry(418),
    ShieldAttack(419),
    DarkLighting(420),
    AttackCountX(421),
    BMageDeath(422),
    BombTime(423),
    NoDebuff(424),
    BattlePvP_Mike_Shield(425),
    BattlePvP_Mike_Bugle(426),
    XenonAegisSystem(427),
    AngelicBursterSoulSeeker(428),
    HiddenPossession(429),
    NightWalkerBat(430),
    NightLordMark(431),
    WizardIgnite(432),
    FireBarrier(433),
    ChangeFoxMan(434),
    PairingUser(435),
    Frenzy(436),
    ShadowSpear(437),
    PvPFlag(438),
    BladeStanceMode(439),
    BladeStancePower(440),
    KenjiCounter(441),
    EvasionMaster(442),
    SelfHyperBodyIncPAD(443),
    SelfHyperBodyMaxHP(444),
    SelfHyperBodyMaxMP(445),
    BladeStanceBooster(446),
    UNK447(447),
    UNK448(448),
    EvasionUpgrade(449),
    CriticalBuffAdd(450),
    FoxBless(451),
    BossDamageRate(452),
    RepeatEffect2(453),
    AntiEvilShield(454),
    TotalDAMr(455),
    GiantBossDeathCnt(456),
    UNK457(457),
    AntiDebuff(458),
    UNK459(459),
    MastemaGuard(460),
    Elysion(461),
    QuiverFullBurst(462),
    SwordBaptism(463),
    WildGrenade(464),
    ChainMantisADV(465),
    FieldGimmickFear(466),
    ImmuneStun(467),
    BattlePvP_Helena_Mark(468),
    BattlePvP_Darklord_Explosion(469),
    BattlePvP_Helena_WindSpirit(470),
    BattlePvP_LangE_Protection(471),
    BattlePvP_LeeMalNyun_ScaleUp(472),
    BattlePvP_Revive(473),
    PinkbeanAttackBuff(474),
    PinkbeanRelax(475),
    PinkbeanRollingGrade(476),
    PinkbeanYoYoStack(477),
    RandAreaAttack(478),
    RandAreaAttack2(479),
    ShineRuneAttack(480),
    NextAttackEnhance(481),
    PirateDesire(482),
    AranCombotempastOption(483),
    ViperTimeLeap(484),
    RoyalGuardState(485),
    BodyRectGuardPrepare(486),
    MichaelSoulLink(487),
    MichaelStanceLink(488),
    TriflingWhimOnOff(489),
    AddRangeOnOff(490),
    KinesisPsychicPoint(491),
    KinesisPsychicOver(492),
    KinesisIncMastery(493),
    KinesisPsychicEnergeShield(494),
    BladeStance(495),
    DebuffActiveSkillHPCon(496),
    DebuffIncHP(497),
    BowMasterMortalBlow(498),
    AngelicBursterSoulResonance(499),
    Fever(500),
    RpSiksin(501),
    TeleportMasteryRange(502),
    FixCoolTime(503),
    IncMobRateDummy(504),
    AdrenalinBoost(505),
    AranDrain(506),
    AranBoostEndHunt(507),
    RWCylinder(508),
    RWCombination(509),
    RWVulkanPunch(510),
    RWMagnumBlow(511),
    RWBarrier(512),
    RWBarrierHeal(513),
    RWMaximizeCannon(514),
    RWOverHeat(515),
    UsingScouter(516),
    RWMovingEvar(517),
    Stigma(518),
    MahaInstall(519),
    HeavensDoorNotTime(520),
    RuneStoneNoTime(521),
    XenonRoketRunch(522),
    TransformOverMan(523),
    EnergyBust(524),
    LightningUnion(525),
    BulletParty(526),
    LoadedDice(527),
    BishopPray(528),
    ChainArtsFury(529),
    MichaelFixDamDecTime(530),
    PinkbeanYoYoAddDamR(531),
    Warrior_AuraWeapon(532),
    Warrior_AuraWeaponStack(533),
    Wizard_OverloadMana(534),
    Michael_RhoAias(535),
    Kinesis_DustTornado(536),
    NightLord_SpreadThrow(537),
    HowlingGaleStack(538),
    CannonShooter_BFCannonBall(539),
    CannonShooter_MiniCannonBall(540),
    Shadower_ShadowAssault(541),
    CreateEventMeso(542),
    MesoRanger_MesoDizerX(543),
    DawnShield_ExHP(544),
    DawnShield_WillCare(545),
    SkillDeployment(546),
    InnerStorm(547),
    Wet(548),
    SpecialTombPL(549),
    GrabbedByMob(550),
    SummonProp(551),
    ReduceMP(552),
    KenjiShadowAttackBuff(553),
    EXP_CARD(554),
    WorldExpBuff(555),
    WorldDropBuff(556),
    CurseRingBuff(557),
    Unk558(558),
    GhostLiberationStack(559),
    KannaSiksinAutoAttack(560),
    FifthAdvWarriorShield(561),
    SplitArrow(562),
    FreudBlessing(563),
    OverloadMode(564),
    FifthSpotLight(565),
    OutSide(566),
    WeaponVariety(567),
    LefGloryWing(568),
    Shadower_Assassination(569),
    ConvertAD(570),
    EtherealForm(571),
    ReadyToDie(572),
    Oblivion(573),
    Cr2CriDamR(574),
    BlackMageCreate(575),
    BlackMageDestroy(576),
    BlackMageMonochrome(577),
    HitStackDamR(578),
    BuffControlDebuff(579),
    DispersionDamage(580),
    HarmonyLink(581),
    LefFastCharge(582),
    BuffIconNoShadow(583),
    CrystalChargeBuffIcon(584),
    LioMachinaCombineBuffIcon(585),
    CoalitionSupportWarplaneBuffIcon(586),
    BattlePvP_Ryude_Frozen(587),
    BattlePvP_Ryude_Buff(588),
    AntiMagicShellByJewelMaking(589),
    DamageRateSetUpForApc(590),
    SpecterGauge(591),
    SpecterMode(592),
    SpellBullet_Plain(593),
    SpellBullet_Scarlet(594),
    SpellBullet_Gust(595),
    SpellBullet_Abyss(596),
    ComingDeath(597),
    GreatOldAbyss(598),
    SixthPhoenix(599),
    HolyAdvent(600),
    ZodiacBurst(601),
    CombatFrenzy(602),
    LPSpellAmplification(603),
    LPInfinitySpell(604),
    LPMagicCircuitFullDrive(605),
    LPMagicCircuitFullDriveStack(606),
    LPBattleMode(606),
    LPHoldSpecterGauge(607),
    DiscoveryWeather(608),
    BossWill_Infection(609),
    PvpApcTeam(610),
    UNK_611(611),
    HolyMagicShellReUse(612),
    StrikerComboStack(613),
    HeroComboInstinct(614),
    KhaliUltimatum(615),
    WindBreakerStormGuard(616),
    FlameWizardInfiniteFlame(617),
    MichaelSwordOfLight(618),
    PhantomMarkOfPhantomOwner(619),
    PhantomMarkOfPhantomTarget(620),
    RescuedSoldierBuffIcon1(621),
    RescuedSoldierBuffIcon2(622),
    FireBirdSupport(623),
    FireBirdSupportActive(624),
    AuraOfLife(625),
    MemoryOfJourney(626),
    MiracleTime(627),
    ItemUpgradeR(628),
    BufftimeRforActive(629),
    DecBaseDamageDebuff(630),
    LimitConsumeDebuff(631),
    LimitEquipStatDebuff(632),
    BlackMageWeaponDestruction(633),
    BlackMageWeaponCreation(634),
    BattlePvP_LangE_LiverStack(635),
    BattlePvP_Mike_Amor(636),
    SiphonVitalityBarrier(637),
    PathFinderAncientGuidance(638),
    BattlePvP_KeyDown(639),
    BattlePvP_Wongki_FlyingCharge(640),
    BattlePvP_Wongki_AwesomeFairy(641),
    BattlePvP_Mugong_PandaZone(642),
    BattleSurvivalDefence(643),
    BattleSurvivalInvincible(644),
    EventPvPDefence(645),
    EventPvPInvincible(646),
    EventSoccerBall(647),
    EventSoccerMomentBuff(648),
    ZeroDamageDebuff(649),
    FifthGoddessBless(650),
    CommonItemSkillContinuous(651),
    PinkbeanMatryoshka(652),
    NewtroWarriors(653),
    SilverMane(654),
    SilverManeBuff(655),
    BattlePVPAttBuff(656),
    MinigameStat(657),
    LuckyPapylus(658),
    AnimaThiefTaoistType(659),
    AnimaThiefTaoistGauge(660),
    AnimaThiefCloneAttack(661),
    AnimaThiefFifthCloneAttack(662),
    AnimaThiefButterfly(663),
    MiracleDrug(664),
    MiracleDrugNoCon(665),
    AnimaThiefMetaphysics(666),
    NoviceMagicianLink(667),
    NerotaPower(668),
    ChampionDoubleUp(669),
    LibraryMissionGuard(670),
    XenonHoloGramGraffiti(671),
    KeyDownEnable(672),
    DracoSlasherNoCooltime(673),
    WillOfSword(674),
    LWSwordGauge(675),
    LWCreation(676),
    LWDike(677),
    LWWonder(678),
    LWRestore(679),
    LefWarriorNobility(680),
    LWResonanceBuff(681),
    RunePurification(682),
    RuneContagion(683),
    DebuffHallucination(684),
    BMageAuraYellow(685),
    BMageAuraDrain(686),
    BMageAuraBlue(687),
    BMageAuraDark(688),
    BMageAuraDebuff(689),
    BMageAuraUnion(690),
    IceAura(691),
    KnightsAura(692),
    ZeroAuraStr(693),
    NovaArcherIncanation(694),
    AnimaThiefMetaphysicsBuff(695),
    RevenantGauge(696),
    DeathDance(697),
    ShadowShield(698),
    AranComboTempestAura(699),
    XenonBursterLaser(700),
    BMageAbyssalLightning(701),
    StrikerThunderChain(702),
    MercedesRoyalKnight(703),
    PhantomDefyingFate(704),
    FWSalamanderMischiefAttack(705),
    KinesisLawOfGravity(706),
    RepeatinCartrige(707),
    LefMageCrystalGate(708),
    ThrowBlasting(709),
    AnimaThiefIllusion(710),
    DarknessAura(711),
    WeaponVarietyFinale(712),
    Equinox(713),
    EquinoxActive(714),
    ZeroEgoWeaponAlpha(715),
    RelicUnboundD(716),
    EvanSpiralOfMana(717),
    RWAfterImage,
    NADragonGauge(718),
    NADragonEnchant(719),
    NADeathBlessing(720),
    NAThanatosDescent(721),
    NAAnnihilation(722),
    NARemainIncense(723),
    NAOminousStream(724),
    NABrutalPang(725),
    MobFlashBang(726),
    IgnorePriestDispel(727),
    LimitRecovery(728),
    NALinkSkill(729),
    StrikerChainReaction(730),
    LimitHealFactor(731),
    AdminCritical(732),
    AdminCriticalDam(733),
    AdminIgnoreTargetDEF(734),
    AdminBDR(735),
    AdminBuffTimeR(736),
    AdminActionSpeed(737),
    AdrenalinActivate(738),
    ATScrollPassive(739),
    YetiFuryGauge(740),
    YetiFuryMode(741),
    YetiMushroom(742),
    YetiMyFriendPepe(743),
    PinkbeanShowTime(744),
    DecFinalDamageDebuff(745),
    AMEarthVeinOnOff(746),
    AMPlanting(747),
    AMStoneShield(748),
    AMAbsorptionRiver(749),
    AMAbsorptionWind(750),
    AMAbsorptionSun(751),
    AMArtificialEarthVein(752),
    IgnoreFrictionOnOff(753),
    AnimaLotus(754),
    AMLinkSkill(755),
    AMEVTeleport(756),
    BossFieldFinalDamR(757),
    StormWhim(758),
    SeaSerpent(759),
    SerpentStone(760),
    SerpentScrew(761),
    FlameSweep(762),
    Cosmos(763),
    EnhancePiercing(764),
    EnhanceSniping(765),
    UltimateSniping(766),
    UltimatePiercing(767),
    EnhanceQuadrupleThrow(768),
    UnwearyingRun(769),
    CrusaderPanic(770),
    IceAuraZone(771),
    HolyWater(772),
    EpicDungeonGauge(773),
    EpicDungeonMiddleBossBarrier(774),
    TriumphFeather(775),
    SixthAngelsRay(776),
    GrandFinale(777),
    WarInTheShade(778),
    FlashMirage(779),
    HolyBlood(780),
    OrbitalExplosion(781),
    DragonSlave(782),
    LimitBreakFinalAttack(783),
    TranscendentLight(784),
    SixthAssassination(785),
    SixthAssassinationDarkSight(786),
    ArtificialEvolution(787),
    SixthFrozenLightning(788),
    KinesisUltimateBPM(789),
    ElementalKnight(790),
    LarknessStop(791),
    SummonChakri(792),
    ShadowAcceleration(793),
    ShadowBurst(794),
    DeceivingBlade(795),
    KaringGoongiAdvantage(796),
    KaringDoolAdvantage(797),
    BossAggro(798),
    Confinement(799),
    GrabAndThrow(800),
    DarkCloud(801),
    FixedSpeedAndJump(802),
    UserAroundAttackDebuff(803),
    UserTrackingAreaWarning(804),
    RPEventStat(805),
    FlameOrbMultiAttack(806),
    SixthStormArrowEx(807),
    SuperFistEnrageStack(808),
    WildVulcanAdv(809),
    WildVulcanAdvStack(810),
    NaturesBelief(811),
    AdrenalinSurge(812),
    LifeDeathControl(813),
    MissileBarrage(814),
    ForsakenRelic(815),
    Nightmare(816),
    LefPirateSpecterMark(817),
    RapidFire(818),
    ElementalFocus(819),
    SacredBastion(820),
    PathFinderForceCompulsion(821),
    AnimaThiefTaoistUpgrade(822),
    AnimaThiefFlameStrike(823),
    BlasterFileBunker(824),
    HowlingOfNature(825),
    KannaFifthAttract(826),
    KannaHakuHide(827),
    NeoTokyoBossThesis(828),
    NeoTokyoBossAntiThesis(829),
    NeoTokyoBossBomb(830),
    NeoTokyoBossPowOfLife(831),
    SixthHakuman(832),
    SixthShinBatto(833),
    DashSpeed(834, true),
    DashJump(835, true),
    RideVehicle(836, true),
    PartyBooster(837, true),
    GuidedBullet(838, true),
    Undead(839, true),
    RideVehicleExpire(840, true),
    UNK_841(841, true),
    RelicGauge(842, true),
    SecondAtomLockOn(843, true),
    ErdaStack(844),
    ErdaRevert(845),
    DescentOfSunRingType(846),
    MukHyunChosic(847),
    MukHyunDivine(848),
    MukHyunSingongCycle(849),
    MukHyun_SEON_PUNG_GAG(850),
    MukHyun_HO_SIN_GANG_GI(851),
    MukHyunNoDivineDec(852),
    MukhyunLinkSkill(853),
    None,
    MukHyunAwakeMushin,
    MukHyunRepeat,
    MukHyun_IM_GI_EUNG_BYEON,
    Unk176_466,
    Unk200_527,
    BattlePvPHelenaMark,
    BattlePvPLangEProtection,
    DivineEcho,
    RhoAias,
    WingsOfGlory,
    LucentBrand,
    Unk199_528,
    Unk202_580,
    Unk205_587,
    Unk205_589,
    Unk188_500,
    Unk199_545,
    WillowDodge,
    EyeForEye,
    Jinsoku,
    HayatoBooster,
    HayatoCr,
    HayatoBoss,
    HayatoPAD,
    HayatoHPR,
    IaijutsuBlade,
    HayatoMPR,
    HayatoStance,
    BattoujutsuAdvance,
    MastemasMark,
    IgnorePCounter,
    PrimalGrenade,
    HowlingCritical,
    HowlingMaxMP,
    HowlingDefence,
    HowlingEvasion,
    BeastFormDamageUp,
    ExtraSkillCTS,
    ZeroAuraSpd,
    RelicEmblem,
    AncientGuidance,
    Unk188_492,
    TridentStrike,
    LightningCascade,
    ComboInstinct,
    LightOfSpirit,
    RiftOfDamnation,
    MahasFury,
    SpreadThrow,
    WindEnergy,
    GaleBarrier,
    Albatross,
    DEF,
    AbyssalCast,
    GustCast,
    ScarletCast,
    BasicCast,
    SpecterState,
    SpecterEnergy,
    AbyssalRecall,
    InfinitySpell,
    ImpendingDeath,
    ChargeSpellAmplifier,
    PhantomMarkMobStat,
    PhantomMark,
    Benediction,
    QuiverBarrage,
    AdvancedQuiver,
    MeltDown,
    Ember,
    OmegaBlaster,
    VoidStrike,
    MuscleMemory,
    KillingPoint,
    TrickBladeMobStat,
    MesoGuard,
    ShadowAssault,
    EnergyCharged,
    FifthGoddessBlessStack,
    IndieWaterSmashBuff,
    IndiePartyExpRate,
    IndieCrMin,
    ComboBarrier,
    BodyPressure,
    ComboUnlimited,
    HiddenHyperLinkMaximization,
    CoronaBuffOverlap;

    private final int value;
    private final int pos;
    public int stat;
    private boolean stacked = false;
    public static final SecondaryStat[] isAuraCTS;
    private int flag;
    private int x;

    private SecondaryStat() {
        this.stat = this.ordinal();
        this.value = 1 << 31 - this.ordinal() % 32;
        this.pos = (int)Math.floor(this.ordinal() / 32);
    }

    private SecondaryStat(boolean stacked) {
        this.stat = this.ordinal();
        this.value = 1 << 31 - this.ordinal() % 32;
        this.pos = (int)Math.floor(this.ordinal() / 32);
        this.stacked = stacked;
    }

    private SecondaryStat(int id) {
        this.stat = id;
        this.value = 1 << 31 - id % 32;
        this.pos = id / 32;
    }

    private SecondaryStat(int id, boolean stacked) {
        this.stat = id;
        this.value = 1 << 31 - id % 32;
        this.pos = id / 32;
        this.stacked = stacked;
    }

    public static Map<SecondaryStat, Integer> getSpawnList() {
        HashMap<SecondaryStat, Integer> SpawnStatsList = new HashMap<SecondaryStat, Integer>();
        SpawnStatsList.put(IndieForceSpeed, 0);
        SpawnStatsList.put(IndieLoopEffect, 0);
        SpawnStatsList.put(IndieBuffIcon, 0);
        SpawnStatsList.put(IndieNotDamaged, 0);
        SpawnStatsList.put(IndieKeydown, 0);
        SpawnStatsList.put(IndieSpecificSkill, 0);
        SpawnStatsList.put(IndieAllHitDamR, 0);
        SpawnStatsList.put(IndieBarrier, 0);
        SpawnStatsList.put(IndieStarForce, 0);
        SpawnStatsList.put(IndieNBDR, 0);
        SpawnStatsList.put(IndieMonsterCollectionR, 0);
        SpawnStatsList.put(IndieAntiMagicShell, 0);
        SpawnStatsList.put(BlessingArmor, 0);
        SpawnStatsList.put(PyramidEffect, 0);
        SpawnStatsList.put(BattlePvP_Helena_Mark, 0);
        SpawnStatsList.put(BattlePvP_LangE_Protection, 0);
        SpawnStatsList.put(PinkbeanRollingGrade, 0);
        SpawnStatsList.put(AdrenalinBoost, 0);
        SpawnStatsList.put(RWBarrier, 0);
        SpawnStatsList.put(Kinesis_DustTornado, 0);
        SpawnStatsList.put(BattlePvP_Ryude_Frozen, 0);
        SpawnStatsList.put(BattlePvP_LangE_LiverStack, 0);
        SpawnStatsList.put(BattlePvP_KeyDown, 0);
        SpawnStatsList.put(EnergyCharged, 0);
        SpawnStatsList.put(DashSpeed, 0);
        SpawnStatsList.put(DashJump, 0);
        SpawnStatsList.put(RideVehicle, 0);
        SpawnStatsList.put(PartyBooster, 0);
        SpawnStatsList.put(GuidedBullet, 0);
        SpawnStatsList.put(Undead, 0);
        SpawnStatsList.put(RideVehicleExpire, 0);
        SpawnStatsList.put(RelicGauge, 0);
        SpawnStatsList.put(SecondAtomLockOn, 0);
        return SpawnStatsList;
    }

    @Override
    public int getPosition() {
        return this.pos;
    }

    @Override
    public int getValue() {
        return this.value;
    }

    public boolean canStack() {
        return this.stacked;
    }

    public String toString() {
        return this.name() + "(" + this.stat + ")";
    }

    public static SecondaryStat getByValue(int value) {
        return Arrays.stream(SecondaryStat.values()).filter(it -> it.stat == value).findFirst().orElse(null);
    }

    public int getFlag() {
        return this.flag;
    }

    public boolean isNormalDebuff() {
        switch (this.ordinal()) {
            case 9: 
            case 97: 
            case 98: 
            case 99: 
            case 111: 
            case 112: 
            case 113: 
            case 153: 
            case 155: 
            case 191: {
                return true;
            }
        }
        return false;
    }

    public boolean isCriticalDebuff() {
        switch (this.ordinal()) {
            case 96: 
            case 114: 
            case 120: 
            case 127: 
            case 134: 
            case 161: 
            case 207: 
            case 247: {
                return true;
            }
        }
        return false;
    }

    public boolean isSpecialBuff() {
        return switch (this.ordinal()) {
            case 836, 837, 838, 839, 840, 841, 842, 844, 845 -> true;
            default -> false;
        };
    }

    public int getX() {
        return this.x;
    }

    public static boolean isEncode4Byte(Map<SecondaryStat, Pair<Integer, Integer>> statups) {
        SecondaryStat[] array;
        for (SecondaryStat stat : array = new SecondaryStat[]{CarnivalDefence, SpiritLink, DojangLuckyBonus, SoulGazeCriDamR, PowerTransferGauge, ReturnTeleport, ShadowPartner, SetBaseDamage, QuiverCatridge, ImmuneBarrier, NaviFlying, Dance, SetBaseDamageByBuff, DotHealHPPerSecond, DotHealMPPerSecond, IncMaxDamage, Cyclone, GrabbedByMob, MagnetArea, PairingUser, MegaSmasher, VampDeath, FifthAdvWarriorShield, RidingExpireInfoSave, RWBarrier, SiphonVitalityBarrier}) {
            if (!statups.containsKey(stat)) continue;
            return true;
        }
        return false;
    }

    public static void main(String[] args) {
        for (SecondaryStat stat : SecondaryStat.values()) {
            stat.change();
        }
        for (int i = 0; i <= SecondaryStat.values()[SecondaryStat.values().length - 1].stat; ++i) {
            SecondaryStat stat = SecondaryStat.getByValue(i);
            if (stat != null) {
                System.out.println(stat.name() + " = " + stat.stat + ",");
                continue;
            }
            System.out.println("\t// " + i);
        }
    }

    private void change() {
        int change = 0;
        if (this.stat >= 64 && this.stat <= 690) {
            change = 1;
        } else if (this.stat >= 691 && this.stat <= 718) {
            change = 2;
        } else if (this.stat >= 719) {
            change = 13;
        }
        this.stat += change;
    }

    static {
        isAuraCTS = new SecondaryStat[]{BMageAuraYellow, BMageAuraBlue, BMageAuraDark, BMageAuraDebuff, KnightsAura, MichaelSoulLink};
    }
}

