/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  Client.BuddylistEntry
 *  Client.CharacterNameAndId
 *  Client.MapleSigninStatus
 *  Client.inventory.MaplePotionPot
 */
package Server.world;

import Client.BuddylistEntry;
import Client.CharacterNameAndId;
import Client.MapleCharacter;
import Client.MaplePvpStats;
import Client.MapleQuestStatus;
import Client.MapleSigninStatus;
import Client.MapleTraitType;
import Client.MapleUnion;
import Client.MonsterFamiliar;
import Client.PlayerSpecialStats;
import Client.VCoreSkillEntry;
import Client.VMatrixSlot;
import Client.anticheat.CheatTracker;
import Client.anticheat.ReportType;
import Client.inventory.Item;
import Client.inventory.MapleImp;
import Client.inventory.MapleInventory;
import Client.inventory.MapleMount;
import Client.inventory.MaplePet;
import Client.inventory.MaplePotionPot;
import Client.skills.InnerSkillEntry;
import Client.skills.SkillEntry;
import Client.skills.SkillMacro;
import Net.server.MapleTrunk;
import Net.server.cashshop.CashShop;
import Net.server.shop.MapleShopItem;
import SwordieX.client.character.keys.FuncKeyMap;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import tools.Pair;

public class CharacterTransfer {
    public final Map<MapleTraitType, Integer> traits = new EnumMap<MapleTraitType, Integer>(MapleTraitType.class);
    public final List<CharacterNameAndId> buddies = new LinkedList<CharacterNameAndId>();
    public final Map<Integer, MapleQuestStatus> Quest = new LinkedHashMap<Integer, MapleQuestStatus>();
    public final Map<Integer, SkillEntry> skills = new LinkedHashMap<Integer, SkillEntry>();
    public final Map<String, Integer> credit;
    public final Map<Byte, Integer> reports = new LinkedHashMap<Byte, Integer>();
    public final List<Pair<Integer, Integer>> quickslot;
    public final Map<Integer, String> InfoQuest;
    public final Map<String, String> KeyValue;
    public final Map<Integer, String> worldShareInfo;
    public final Map<Integer, VCoreSkillEntry> vcoreskills = new LinkedHashMap<Integer, VCoreSkillEntry>();
    public final Map<Integer, VMatrixSlot> vMatrixSlot;
    public Map<Integer, Pair<Integer, SkillEntry>> sonOfLinedSkills = new LinkedHashMap<Integer, Pair<Integer, SkillEntry>>();
    public Map<Integer, FuncKeyMap> funcKeyMaps = new LinkedHashMap<Integer, FuncKeyMap>();
    public int characterid;
    public int accountid;
    public int fame;
    public int pvpExp;
    public int pvpPoints;
    public int hair;
    public int face;
    public int mapid;
    public int guildid;
    public int partyid;
    public int messengerid;
    public int maplePoint;
    public int mount_itemid;
    public int mount_exp;
    public int points;
    public int vpoints;
    public int marriageId;
    public int maxhp;
    public int maxmp;
    public int hp;
    public int mp;
    public int friendshiptoadd;
    public int familyid;
    public int seniorid;
    public int junior1;
    public int junior2;
    public int currentrep;
    public int totalrep;
    public int gachexp;
    public int guildContribution;
    public int totalWins;
    public int totalLosses;
    public int todayonlinetime;
    public int totalonlinetime;
    public int weaponPoint;
    public int channel;
    public byte gender;
    public byte guildrank;
    public byte alliancerank;
    public byte buddysize;
    public byte world;
    public byte initialSpawnPoint;
    public byte skinColor;
    public byte mount_level;
    public byte mount_Fatigue;
    public byte subcategory;
    public long lastfametime;
    public long TranferTime;
    public long exp;
    public long meso;
    public String name;
    public String accountname;
    public String BlessOfFairy;
    public String BlessOfEmpress;
    public String chalkboard;
    public String tempIP;
    public int level;
    public int gmLevel;
    public short str;
    public short dex;
    public short int_;
    public short luk;
    public short remainingAp;
    public short hpApUsed;
    public short mpApUsed;
    public short job;
    public short fatigue;
    public int soulcount;
    public MapleInventory[] inventorys;
    public SkillMacro[] skillmacro = new SkillMacro[5];
    public MapleTrunk storage;
    public CashShop cs;
    public CheatTracker anticheat;
    public InnerSkillEntry[] innerSkills;
    public int[] savedlocation;
    public int[] wishlist;
    public int[] rocks;
    public int[] remainingSp;
    public int[] regrocks;
    public int[] hyperrocks;
    public int[] friendshippoints;
    public MaplePet[] spawnPets;
    public MapleImp[] imps;
    public List<Integer> famedcharacters = null;
    public List<Integer> battledaccs = null;
    public List<MapleShopItem> rebuy = null;
    public int decorate;
    public int beans;
    public int warning;
    public int reborns;
    public int reborns1;
    public int reborns2;
    public int reborns3;
    public int apstorage;
    public int honor;
    public int love;
    public long lastLoveTime;
    public Map<Integer, Long> loveCharacters = null;
    public int playerPoints;
    public int playerEnergy;
    public MaplePvpStats pvpStats;
    public int pvpDeaths;
    public int pvpKills;
    public int pvpVictory;
    public MaplePotionPot potionPot;
    public PlayerSpecialStats SpecialStats;
    public MapleSigninStatus signinStatus;
    public List<Integer> effectSwitch;
    public List<MonsterFamiliar> familiars;
    public Map<Byte, List<Item>> extendedSlots = null;
    public long ltime;
    public MapleUnion mapleUnion;
    public MonsterFamiliar summonedFamiliar;
    public long loginTime;
    public int onlineTime;
    public int soulSkillID;
    public short soulOptionID;
    public int soulMP;
    public int maxSoulMP;
    public Map<Integer, List<Integer>> salon;
    public Map<Integer, Pair<Integer, Long>> fairys;
    public int burningChrType;
    public long burningChrTime;

    public CharacterTransfer() {
        this.famedcharacters = new ArrayList<Integer>();
        this.battledaccs = new ArrayList<Integer>();
        this.extendedSlots = new HashMap<Byte, List<Item>>();
        this.loveCharacters = new LinkedHashMap<Integer, Long>();
        this.rebuy = new ArrayList<MapleShopItem>();
        this.KeyValue = new LinkedHashMap<String, String>();
        this.InfoQuest = new LinkedHashMap<Integer, String>();
        this.worldShareInfo = new LinkedHashMap<Integer, String>();
        this.quickslot = new ArrayList<Pair<Integer, Integer>>();
        this.credit = new LinkedHashMap<String, Integer>();
        this.vMatrixSlot = new TreeMap<Integer, VMatrixSlot>();
        this.salon = new HashMap<Integer, List<Integer>>();
    }

    public CharacterTransfer(MapleCharacter chr) {
        this(chr, chr.getClient().getChannel());
    }

    public CharacterTransfer(MapleCharacter chr, int channel) {
        this.characterid = chr.getId();
        this.accountid = chr.getAccountID();
        this.accountname = chr.getClient().getAccountName();
        this.maplePoint = chr.getClient().getMaplePoints();
        this.gmLevel = chr.getClient().getGmLevel();
        this.channel = channel;
        this.vpoints = chr.getVPoints();
        this.name = chr.getName();
        this.fame = chr.getFame();
        this.love = chr.getLove();
        this.gender = chr.getGender();
        this.level = chr.getLevel();
        this.str = chr.getStat().getStr();
        this.dex = chr.getStat().getDex();
        this.int_ = chr.getStat().getInt();
        this.luk = chr.getStat().getLuk();
        this.hp = chr.getStat().getHp();
        this.mp = chr.getStat().getMp();
        this.maxhp = chr.getStat().getMaxHp(false);
        this.maxmp = chr.getStat().getMaxMp(false);
        this.exp = chr.getExp();
        this.hpApUsed = chr.getHpApUsed();
        this.mpApUsed = chr.getMpApUsed();
        this.remainingAp = chr.getRemainingAp();
        this.remainingSp = chr.getRemainingSps();
        this.meso = chr.getMeso();
        this.pvpExp = chr.getTotalBattleExp();
        this.pvpPoints = chr.getBattlePoints();
        this.skinColor = chr.getSkinColor();
        this.job = chr.getJob();
        this.hair = chr.getHair();
        this.face = chr.getFace();
        this.mapid = chr.getMapId();
        this.initialSpawnPoint = chr.getInitialSpawnpoint();
        this.marriageId = chr.getMarriageId();
        this.world = chr.getWorld();
        this.guildid = chr.getGuildId();
        this.guildrank = chr.getGuildRank();
        this.guildContribution = chr.getGuildContribution();
        this.alliancerank = chr.getAllianceRank();
        this.points = chr.getPoints();
        this.fairys = chr.getFairys();
        this.spawnPets = chr.getSpawnPets();
        this.subcategory = chr.getSubcategory();
        this.imps = chr.getImps();
        this.fatigue = chr.getFatigue();
        this.currentrep = chr.getCurrentRep();
        this.totalrep = chr.getTotalRep();
        this.totalWins = chr.getTotalWins();
        this.totalLosses = chr.getTotalLosses();
        this.gachexp = chr.getGachExp();
        this.anticheat = chr.getCheatTracker();
        this.tempIP = chr.getClient().getTempIP();
        this.rebuy = chr.getRebuy();
        this.decorate = chr.getDecorate();
        this.beans = chr.getBeans();
        this.warning = chr.getWarning();
        this.reborns = chr.getReborns();
        this.reborns1 = chr.getReborns1();
        this.reborns2 = chr.getReborns2();
        this.reborns3 = chr.getReborns3();
        this.apstorage = chr.getAPS();
        this.honor = chr.getHonor();
        this.playerPoints = chr.getPlayerPoints();
        this.playerEnergy = chr.getPlayerEnergy();
        this.pvpDeaths = chr.getPvpDeaths();
        this.pvpKills = chr.getPvpKills();
        this.pvpVictory = chr.getPvpVictory();
        this.friendshiptoadd = chr.getFriendShipToAdd();
        this.friendshippoints = chr.getFriendShipPoints();
        this.soulcount = chr.getSoulMP();
        this.summonedFamiliar = chr.getSummonedFamiliar();
        for (MapleTraitType t : MapleTraitType.values()) {
            this.traits.put(t, chr.getTrait(t).getTotalExp());
        }
        for (BuddylistEntry buddylistEntry : chr.getBuddylist().getBuddies()) {
            this.buddies.add(new CharacterNameAndId(buddylistEntry.getCharacterId(), buddylistEntry.getName(), buddylistEntry.getGroup(), buddylistEntry.isVisible()));
        }
        for (Map.Entry entry : chr.getReports().entrySet()) {
            this.reports.put(((ReportType)((Object)entry.getKey())).i, (Integer)entry.getValue());
        }
        this.buddysize = chr.getBuddyCapacity();
        this.partyid = chr.getParty() == null ? -1 : chr.getParty().getId();
        this.messengerid = chr.getMessenger() != null ? chr.getMessenger().getId() : 0;
        this.KeyValue = chr.getKeyValue_Map();
        this.InfoQuest = chr.getInfoQuest_Map();
        this.worldShareInfo = chr.getWorldShareInfo();
        for (Map.Entry entry : chr.getQuest_Map().entrySet()) {
            this.Quest.put((Integer)entry.getKey(), (MapleQuestStatus)entry.getValue());
        }
        this.inventorys = chr.getInventorys();
        chr.getSkills().forEach(this.skills::put);
        chr.getSonOfLinkedSkills().forEach(this.sonOfLinedSkills::put);
        chr.getVCoreSkill().forEach(this.vcoreskills::put);
        this.SpecialStats = chr.getSpecialStat();
        this.BlessOfFairy = chr.getBlessOfFairyOrigin();
        this.BlessOfEmpress = chr.getBlessOfEmpressOrigin();
        this.chalkboard = chr.getChalkboard();
        this.skillmacro = chr.getMacros();
        this.innerSkills = chr.getInnerSkills();
        this.funcKeyMaps = chr.getFuncKeyMaps();
        this.quickslot = chr.getQuickSlot().Layout();
        this.savedlocation = chr.getSavedLocations();
        this.wishlist = chr.getWishlist();
        this.rocks = chr.getRocks();
        this.regrocks = chr.getRegRocks();
        this.hyperrocks = chr.getHyperRocks();
        this.famedcharacters = chr.getFamedCharacters();
        this.battledaccs = chr.getBattledCharacters();
        this.lastfametime = chr.getLastFameTime();
        this.storage = chr.getTrunk();
        this.pvpStats = chr.getPvpStats();
        this.potionPot = chr.getPotionPot();
        this.cs = chr.getCashInventory();
        this.extendedSlots = chr.getAllExtendedSlots();
        MapleMount mount = chr.getMount();
        this.mount_itemid = mount.getItemId();
        this.mount_Fatigue = mount.getFatigue();
        this.mount_level = mount.getLevel();
        this.mount_exp = mount.getExp();
        this.lastLoveTime = chr.getLastLoveTime();
        this.loveCharacters = chr.getLoveCharacters();
        this.TranferTime = System.currentTimeMillis();
        this.todayonlinetime = chr.getTodayOnlineTime();
        this.totalonlinetime = chr.getTotalOnlineTime();
        this.weaponPoint = chr.getWeaponPoint();
        this.credit = chr.getCredits();
        this.signinStatus = chr.getSigninStatus();
        this.effectSwitch = chr.getEffectSwitch();
        this.familiars = chr.getFamiliars();
        this.ltime = chr.getLTime();
        this.mapleUnion = chr.getMapleUnion();
        this.vMatrixSlot = chr.getVMatrixSlot();
        this.loginTime = chr.getLoginTime();
        this.onlineTime = chr.getLastOnlineTime();
        this.soulMP = chr.getSoulMP();
        this.soulSkillID = chr.getSoulSkillID();
        this.soulOptionID = chr.getSoulOption();
        this.maxSoulMP = chr.getMaxSoulMP();
        this.salon = chr.getSalon();
        this.burningChrType = chr.getBurningChrType();
        this.burningChrTime = chr.getBurningChrTime();
    }
}

