/*
 * Decompiled with CFR 0.152.
 */
package Opcode.Opcode;

public enum EffectOpcode {
    UserEffect_LevelUp(0),
    UserEffect_SkillUse(1),
    UserEffect_SkillUseBySummoned(2),
    UserEffect_SkillAffected(4),
    UserEffect_SkillAffected_Ex(5),
    UserEffect_SkillAffected_Select(6),
    UserEffect_SkillSpecialAffected(7),
    UserEffect_Quest(8),
    UserEffect_Pet(9),
    UserEffect_SkillSpecial(10),
    UserEffect_Resist(11),
    UserEffect_ProtectOnDieItemUse(12),
    UserEffect_PlayPortalSE(14),
    UserEffect_JobChanged(15),
    UserEffect_QuestComplete(16),
    UserEffect_IncDecHPEffect(17),
    UserEffect_BuffItemEffect(18),
    UserEffect_SquibEffect(19),
    UserEffect_MonsterBookCardGet(20),
    UserEffect_LotteryUse(21),
    UserEffect_ItemLevelUp(22),
    UserEffect_ItemMaker(23),
    UserEffect_ExpItemConsumed(25),
    UserEffect_FieldExpItemConsumed(26),
    UserEffect_ReservedEffect(27),
    UserEffect_UpgradeTombItemUse(28),
    UserEffect_BattlefieldItemUse(29),
    UserEffect_AvatarOriented(30),
    UserEffect_AvatarOrientedRepeat(31),
    UserEffect_AvatarOrientedMultipleRepeat(32),
    UserEffect_IncubatorUse(33),
    UserEffect_PlaySoundWithMuteBGM(34),
    UserEffect_PlayExclSoundWithDownBGM(35),
    UserEffect_SoulStoneUse(36),
    UserEffect_IncDecHPEffect_EX(37),
    UserEffect_IncDecHPRegenEffect(38),
    UserEffect_EffectUOL(39),
    UserEffect_PvPRage(48),
    UserEffect_PvPChampion(49),
    UserEffect_PvPGradeUp(50),
    UserEffect_PvPRevive(51),
    UserEffect_JobEffect(52),
    UserEffect_FadeInOut(53),
    UserEffect_MobSkillHit(54),
    UserEffect_AswanSiegeAttack(55),
    UserEffect_BlindEffect(56),
    UserEffect_BossShieldCount(57),
    UserEffect_ResetOnStateForOnOffSkill(58),
    UserEffect_JewelCraft(59),
    UserEffect_ConsumeEffect(60),
    UserEffect_PetBuff(61),
    UserEffect_LotteryUIResult(62),
    UserEffect_LeftMonsterNumber(63),
    UserEffect_ReservedEffectRepeat(64),
    UserEffect_RobbinsBomb(65),
    UserEffect_SkillMode(66),
    UserEffect_ActQuestComplete(67),
    UserEffect_Point(68),
    UserEffect_SpeechBalloon(69),
    UNK_v258_70(71),
    UNK_v258_71(72),
    UNK_v258_72(73),
    UserEffect_TextEffect(74),
    UNK_v245_71(75),
    UserEffect_SkillPreLoopEnd(75),
    UNK_v245_73(76),
    UserEffect_Aiming(77),
    UNK_v245_75(78),
    UserEffect_PickUpItem(79),
    UserEffect_BattlePvP_IncDecHp(80),
    UserEffect_BiteReceiveSuccess(81),
    UserEffect_BiteReceiveFail(82),
    UserEffect_IncDecHPEffect_Delayed(83),
    UserEffect_Lightness(84),
    UserEffect_HakuSkill(85),
    UNK_v245_83(86),
    UNK_v245_84(87),
    UNK_v245_85(88),
    UNK_v245_86(89),
    UNK_v245_87(90),
    UNK_v245_88(91),
    UserEffect_HoYoungHeal(92),
    UNK_v245_90(93),
    UNK_v245_91(94),
    UNK_v245_92(95),
    UNK_v245_93(96),
    UserEffect_SpeedMirage(97),
    UNK_v258_99(99),
    UNK_v258_100(100),
    UNK_v258_101(101),
    UNK_v258_103(103),
    UNK_v258_104(104),
    UNK_v258_105(105);

    private final short code;

    private EffectOpcode(int code) {
        this.code = (short)code;
    }

    public short getValue() {
        return this.code;
    }
}

