/*
 * Decompiled with CFR 0.152.
 */
package Config.constants.enums;

public enum SecurityCheckType {
    SECURITYPACKET_MEMORY_CHECK(0),
    SECURITYPACKET_FULL_MEMORY_CHECK(1),
    SECURITYPACKET_CHECK_CLIENT_INTEGRITY(2),
    SECURITYPACKET_CHECK_CLIENT_UPDATE_INTERVAL(3),
    SECURITYPACKET_CLIENT_VERSION(4),
    SECURITYPACKET_LOGPACKET(5),
    SECURITYPACKET_NGS_CLIENTTOSERVER(6),
    SECURITYPACKET_NGS_SERVERTOCLIENT(7),
    SECURITYPACKET_NGS_CRASHCLIENT(8),
    SECURITYPACKET_NGS_MIDBLOCKCRASHCLIENT(9),
    SECURITYPACKET_HSHIELD_CRASHCLIENT(10),
    SECURITYPACKET_AUTH_HSHIELD(11),
    SECURITYPACKET_REQUESTCHECKCLIENTINTEGRITY(12),
    SECURITYPACKET_XIGNCODE_CLIENTTOSERVER(13),
    SECURITYPACKET_XIGNCODE_SERVERTOCLIENT(14);

    public final byte value;

    private SecurityCheckType(int value) {
        this.value = (byte)value;
    }
}

